### ISSUE TITLE
Infinite scrollish

### ISSUE THREAD

**Issue by Smokinglirare** [cme-osuka/webbmobilapplikation#1]
Värmer upp Issues för den här kursen. Tänkte börja bygga en sida åt ett par kompisar och min tanke är att ha en startsida som är ganska avlång med typ:

//  Navbar 
//  Hero 
//  Nyheter 
//  Osv 
//  Footer  

Men jag vill inte att allt renderar direkt när man besöker hemsidan utan enbart Navbar och Hero exempelvis, men när man skrollar så laddar Nyheter osv. Detta måste ju vara någon form av infinite scroll, men ändå inte.  Någon som byggt såhär förut och vet om det finns något bra paket för React som löser det?

**Comment by sawariz0r** [comment]
Ta en titt på https://www.react-reveal.com/ :)

**Comment by Smokinglirare** [comment]
Ska spana, tackar.
