### ISSUE TITLE
K1: Frågor och funderingar

### ISSUE THREAD

**Issue by sawariz0r** [cme-osuka/webbmobilapplikation#2]
Har du frågor eller funderingar rörande Kunskapskontroll 1?

Då är du på rätt ställe. Här samlar vi frågor och funderingar så alla kan gå tillbaka och ta del av dessa under K1's gång!

**Comment by linda-94-andersson** [comment]
"Den ska vara byggd för en mobil-webbläsare i första hand (och behöver inte innehålla styling för desktop)."

Finns det något krav på vilken size det ska vara för mobile? Vilken dimension kommer användas under kontrollen?

**Comment by linda-94-andersson** [comment]
Jag ser inget krav på deployment, stämmer det att det räcker med ha ett Git repo och du kommer testa med Localhost?

**Comment by linda-94-andersson** [comment]
Ska man göra en kommentar eller en ny issue?

**Comment by linda-94-andersson** [comment]
Ska man göra en kommentar eller en ny issue om man har frågor/funderingar?
