### ISSUE TITLE
Mobilanpassning 

### ISSUE THREAD

**Issue by linda-94-andersson** [cme-osuka/webbmobilapplikation#3]
"Den ska vara byggd för en mobil-webbläsare i första hand (och behöver inte innehålla styling för desktop). "

Finns det något krav på size på mobile? 
Vilken dimension kommer användas för kontrollen?

**Comment by sawariz0r** [comment]
Det finns inget krav på storlek, men jag kommer eventuellt köra den med preseten "iPhone 12 Pro" (390x844) eller om man själv anger en preset/mått man jobbat med :)

**Comment by linda-94-andersson** [comment]
Tack för svar!
