### ISSUE TITLE
Definiera kravet på att ta bort en tidtagning 

### ISSUE THREAD

**Issue by linda-94-andersson** [cme-osuka/webbmobilapplikation#7]
Ett av kraven är:  "**Ta bort en tidtagning**". 
Betyder det att man ska kunna ta bort en timelog från DB filen? 
Eller kan det betyda att man nollställer en tidtagning? 

Jag tycker det känns konstigt att en användare ska kunna ta bort en timelog från databasen helt själv. 
Vad är vitsen med den task utan timelog som blir kvar? 
Vad händer om användaren vill starta den igen? 
Då måste man bygga in att man kan lägga till timelog igen? 
Jag har tex i min timelog också ett datum som är knutet till när tasken skapades för att kunna rendera ut det i kalendern. Blir väldigt konstigt då om användaren kan ta bort den datan och får en task i "limbo".

` "tasks": [
    {
      "id": "59169946-0199-40d2-aac3-932a4a48a541",
      "name": "Jag syns den 7 okt",
      "projectId": "51e295ee-80c3-44ea-b919-98a39350b8e1"
    }
]`

`"timelogs": [
    {
      "id": "7c45b1cd-52c1-4529-8c2b-53e7cc3c5a6a",
      "startDate": 1665093600000,
      "startTime": "16:26:19",
      "endTime": "16:26:22",
      "taskId": "59169946-0199-40d2-aac3-932a4a48a541"
    }
]`

Personligen tycker jag att det borde "bara" vara att man nollställer start och stop tiden till null/00:00.

**Comment by sawariz0r** [comment]
Jag hade föredragit att kunna ta bort en enskild timelog, exempelvis ifall jag har en task som jag räknar tid på - men sedan inser att jag valt fel, då vill jag kunna ta bort en felaktig tid på en specifik task :)

Och skulle jag vilja starta en (eller vill jobba på en annan, och gå tillbaka till samma task senare), så hade jag isåfall skapat ytterligare en timelog knuten till den tasken. Så att en task ska kunna ha ett obegränsat antal timelogs. 
(Där start/endTime skulle innehålla datum+tid istället för ett enskilt datum, och separat tid) :)

**Däremot,**
om du väljer att nolla start och stopp i din implementation, så är det ok :)

**Comment by linda-94-andersson** [comment]
Jo jag tänkte lite på saken och håller nog med att lägga till flera timelogs per task är nog det man vill ha. 
Det blir nog lättare att räkna ihop total tid då också. 
Men! 
Om du tar bort alla logtimes från en task, hur vet man då när tasken ska synas tex i kalendern? 
Tänker att jag lägger ett start datum direkt på create task och bara har tid i timelogs'en så borde det bli bästa av två världar?

**Comment by linda-94-andersson** [comment]
Diskuterades på handlings tid. 
Svaret är att det är OK att göra som jag vill med datum på tasken för att rendera ut per datum i timer vyn. 
Det ända kravet som finns är att man ska kunna se tasks med aktiva timers i tex kalendern.
