### ISSUE TITLE
Återuppta timer på page refresh

### ISSUE THREAD

**Issue by M00NB3VM** [cme-osuka/webbmobilapplikation#8]
Jag har en useEffect som kollar ifall jag har något i local storage. Om jag har det vill jag återuppta min timer. Detta fungerar ifall jag bläddrar bland mina sidor i appen eller går ur appen, återkommer till t.ex landningssidan och sedan går till min timer. Däremot fungerar det inte om timersidan uppdateras eller om jag går ur appen och sedan direkt in på timersidan.

Problemet verkar vara att min array med timers (och ibland men sällan också min array med tasks) inte hunnit hämtats än. 

Jag har försökt med en egen liten loader via en setState, flyttat runt mina funktioner och dylikt men får det inte att fungera. 

Finns det ett sätt att vänta på att min array har fått sin data innan useEffecten, eller annan funktion körs? (om jag har något i local storage betyder det att min array med timers inte är tom, men som sagt har den inte hunnit att få sin data ännnu).
![printsc](https://user-images.githubusercontent.com/92476062/198322289-e6540623-4081-41af-a178-84fd9c0209e3.png)

**Comment by sawariz0r** [comment]
Använde du `Promise.all()` när du skapade ett loading-state? För vi kan ju se till att flera promises blir klara innan vi fortsätter med hjälp av Promise.all :)

Till exempel:
```js
const { getTimers, setTimersLoading } = useContext1()
const { getTasks, setTasksLoading } = useContext2()

Promise.all([
  getTimers(),
  getTasks()
]).then(() => {
  setTimersLoading(false)
  setTasksLoading(false)
})
```

Det skulle man kunna köra i till exempel en useEffect någonstans som inte renderas om, till exempel i App.js eller liknande tänker jag. Man skulle kunna ta steget längre och visa en loading spinner ifall dessa inte laddas, innan man renderar ut applikationen (dock inte en supersnygg lösning) :) 

För det jag tycker det låter som, är att du behöver eliminera risken att någon av de två inte hämtats innan du börjar jobba med dom

**Comment by M00NB3VM** [comment]
Jag gjorde en promise all i filen där mina första hämtningar sker, det fungerade.
