### ISSUE TITLE
Frågor och funderingar kring K2

### ISSUE THREAD

**Issue by sawariz0r** [cme-osuka/webbmobilapplikation#9]

**Comment by alvablot** [comment]
Om jag har alla fetch-anrop med axios i en funktion i  en separat fil, och inte vill returnera responsen utan sätta staten direkt. Hur gör jag då? Eftersom react klagar när jag hämtar context-staten när det är utanför en komponent.

**Comment by sawariz0r** [comment]
> Om jag har alla fetch-anrop med axios i en funktion i  en separat fil, och inte vill returnera responsen utan sätta staten direkt. Hur gör jag då? Eftersom react klagar när jag hämtar context-staten när det är utanför en komponent.

Just det blir nog svårt, eftersom anropen inte är inuti contexten.. Där hade jag eventuellt skapat funktioner inuti min context som kallar på funktionen du skrivit i den filen med axios-anropet. Som sedan sätter statet inifrån contexten :)

**Comment by alvablot** [comment]
Oki. Får testa det. Tack!

**Comment by alvablot** [comment]
Vad har jag missat här?
<img width="822" alt="Namnlöst" src="https://user-images.githubusercontent.com/89981142/202844192-0d26a1c1-a8aa-4c68-8b1b-3c7ab4b3f8dd.png">

**Comment by alvablot** [comment]
![bild](https://user-images.githubusercontent.com/89981142/202844277-e723ad91-05d3-465b-9d97-8addd2c371b4.png)

**Comment by alvablot** [comment]
Jag löste det. Men är det ok att använda <any> här då?

![bild](https://user-images.githubusercontent.com/89981142/202845026-48ca72fe-2ad1-4885-ad84-7906371e1e85.png)

**Comment by alvablot** [comment]
Fast nu la jag in hela axios-funtionen i context-filen. Var väl inte riktigt så du menade.

**Comment by Smokinglirare** [comment]
Försöker skriva ut en vanlig p tag <p className={styles.timprisText}>Timpris: {sum} SEK</p>

Men får fel "This JSX tag's 'children' prop expects a single child of type 'ReactNode', but multiple children were provided.". 

Fattar inte riktigt för längre ner på sidan skriver jag ut <p className={styles.timprisText}>Kostnad: {amount} SEK</p> utan problem och både amount och sum är number.

**Comment by alvablot** [comment]
Kan du ta en dump på koden?

**Comment by Smokinglirare** [comment]
![Screenshot_100](https://user-images.githubusercontent.com/92430927/203785653-7a6045e4-9f8e-4b49-9226-35f05c741478.jpg)

Vanlig useState ` const [sum, setSum] = useState<Number>(0);  `

**Comment by alvablot** [comment]
får du samma fel om du flyttar ner den i div-elementet?

**Comment by Smokinglirare** [comment]
Löste det, stor bokstav på number var felet. Sorry att jag slösade din tid på klantmisstag.

**Comment by sawariz0r** [comment]
> Löste det, stor bokstav på number var felet. Sorry att jag slösade din tid på klantmisstag.

Happens to all of us! Ibland behöver man bara ett par extra ögon :)

**Comment by Smokinglirare** [comment]
Oscar när du ändå är här, hur nitisk kommer du vara på responsiviteten? Mobil och data funkar? Mitt spann 500px - 800px bredd ser halvbra ut just nu, men är det värt att lägga tid på att fixa?

**Comment by sawariz0r** [comment]
Mobil och desktop räcker :)
